// Hand-authored ASCII pieces for the gallery + auto-loaded ASCII video
// works (generated by `pnpm video:build` into src/content/works/*.json).
// Video works have a `frames` array; the gallery program animates them at
// `fps`. Static works just expose `art`.

export interface GalleryWork {
  title: string;
  year: string;
  caption: string;
  art?: string;                                 // static piece — single ASCII string
  frames?: string[];                            // resolved frames (once loaded)
  fps?: number;
  isVideo?: boolean;                            // true → load via `loader` before showing
  loader?: () => Promise<{
    title: string; year: string; caption: string; fps: number; frames: string[];
  }>;
}

// ASCII-video works: lazy-loaded. Each JSON ends up in its own bundle chunk
// so the main app doesn't have to ship 4+ MB of frame data on first load.
// Until a work is loaded we represent it as a placeholder that knows its
// title/year/caption (read from a sibling .meta.json if present) plus a
// loader to fetch the actual frames on demand.
interface VideoWorkJson {
  title: string;
  year: string;
  caption: string;
  fps: number;
  frames: string[];
}

const VIDEO_LOADERS = import.meta.glob<{ default: VideoWorkJson }>(
  '../../content/works/*.json',
);

function idFromPath(p: string): string {
  // ".../content/works/aevum.json" → "aevum"
  const m = p.match(/([^/\\]+)\.json$/);
  return (m ? m[1] : p).toLowerCase();
}

function titleFromId(id: string): string {
  return id.replace(/_/g, ' ');
}

const VIDEO_WORKS: GalleryWork[] = Object.entries(VIDEO_LOADERS)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([p, loader]) => {
    const id = idFromPath(p);
    return {
      title: titleFromId(id),
      year: '—',
      caption: '',
      isVideo: true,
      loader: async () => {
        const mod = await loader();
        return mod.default;
      },
    } as GalleryWork;
  });

const STATIC_WORKS: GalleryWork[] = [
  {
    title: 'Harbor at 4am',
    year: '2023',
    caption: 'minimal. waiting for wind.',
    art: String.raw`
                                                          .
                                                          |
                                                         /|
                                                        / |
                                                       /  |
                                                      /   |
                                                  ___/____|___
            .                                    /            \
                                                /              \
   ~  ~~   ~  ~~  ~~~  ~ ~  ~~  ~~  ~~  ~  ~~ ~~ ~~ ~~ ~ ~~ ~~~ ~ ~~  ~~  ~~
~~ ~~~  ~~~~  ~~ ~~ ~  ~~~  ~~  ~ ~~~ ~~ ~~~  ~ ~~  ~~  ~~ ~~~ ~~~  ~~~ ~~ ~
 ~~~  ~~  ~~  ~~~ ~~ ~~~~  ~  ~~ ~~~  ~~ ~  ~~~ ~~ ~~~ ~~~  ~~ ~~  ~~~  ~~~~
~~~ ~~~ ~~~  ~~~  ~~  ~~ ~~~ ~~~ ~~  ~~~ ~~~  ~~ ~ ~~ ~~~ ~~  ~~~ ~~ ~~~ ~`,
  },
  {
    title: 'Latent Walk I',
    year: '2022',
    caption: 'istanbul, generative series. seeded by a tuesday.',
    art: String.raw`
   .  ´  ' ,   .   ´  ,   .   '  ´  .   '   .   ,   .   ´
 ´   .   '   ,  .   ´   .  '   ,  .   ´   ,   '  .   ´   ,
   ´   .  '   ;   .  ,  ´   .   ,  ´  .  ;   '  ´   .   '
 ,  .   ,    ' ,   :   ;   ,   ;  :   ,  '   ;   .   ,  ,
   ´   '   ,   :   ;    :    ;   :    ;  ,  ´   ,  '   ´
 .   ,  ´  ;   :    ╱     ╲    :   ;  ´   '   .  ,   .  ´
   ;  .   ,   :   ╱   ◦     ╲   :  ,   ;   ´   ;   ,   ´
 '   .  ´   ,   ╱   o    .    ╲   ,  '   .   ,   ´   .
   ,  ´   ;   ╱   .    o    '    ╲  ;  ´   ,  '   ;   ´
 .   ,  ´  ,   :   ;   :    ,    '   ;  :   ;   ´   ,   '
   ´   .  '   ,   :  ;  ´   .   ;  ´  :  ,   ´   .   ,
 ´   .   '   ,  .   :   .  '   ,  .   ´   ,   '  .   ´   ,
   .  ´  ' ,   .   ´  ,   .   '  ´  .   '   .   ,   .   ´`,
  },
  {
    title: 'Currency Experiment, panel 3',
    year: '2024',
    caption: 'all the units, struck through.',
    art: String.raw`
    ┌─────────────────────────────────────────────────────────┐
    │                                                         │
    │   ₺      $      €      ¥      ₿      ₽      ₹      ฿   │
    │   ─      ─      ─      ─      ─      ─      ─      ─   │
    │                                                         │
    │   $      €      ¥      ₿      ₽      ₹      ฿      ₺   │
    │   ─      ─      ─      ─      ─      ─      ─      ─   │
    │                                                         │
    │   €      ¥      ₿      ₽      ₹      ฿      ₺      $   │
    │   ─      ─      ─      ─      ─      ─      ─      ─   │
    │                                                         │
    │   ¥      ₿      ₽      ₹      ฿      ₺      $      €   │
    │   ─      ─      ─      ─      ─      ─      ─      ─   │
    │                                                         │
    │              none of these are real money.              │
    │                                                         │
    └─────────────────────────────────────────────────────────┘`,
  },
  {
    title: 'Three Sails',
    year: '2023',
    caption: 'a regatta you almost won.',
    art: String.raw`
                            .
                           /|
                          / |
                         /  |              .
                        /   |             /|
                       /    |            / |
                      /     |           /  |        .
                     /______|          /   |       /|
                    /       |         /    |      / |
                   /        |        /     |     /  |
                  /         |       /______|    /   |
                  ----------         |   |     /    |
                                     |   |    /     |
                                     |   |   /______|
                                     ----    |   |
                                              |   |
                                              ----
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ~ ~~ ~~~ ~~ ~~~ ~ ~~ ~~ ~~~ ~ ~~ ~~~ ~~ ~ ~~ ~~~ ~~ ~ ~~ ~~~ ~~ ~~ ~ ~~ ~
~~~ ~ ~~ ~~~ ~~ ~~ ~ ~~~ ~~ ~~~ ~~ ~~ ~ ~~~ ~~ ~~ ~~~ ~~ ~ ~~ ~~~ ~~ ~~ ~~~`,
  },
  {
    title: 'Zero Bytes',
    year: '2024',
    caption: 'one filled cell. the rest is the work.',
    art: String.raw`
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . ▓ . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
   . . . . . . . . . . . . . . . . . . . . . . . . . . . . .`,
  },
  {
    title: 'Rope, Knotted',
    year: '2022',
    caption: 'a bowline, the only knot worth learning.',
    art: String.raw`
                  ____
                 /    \
                /      \
               |    ____|____
               |   /    .    \
                \_/    /|\    \
                  \   / | \   /
                   \_/  |  \_/
                        |
                        |
                        |
                        |
                        |
                        |
                        |
                        |__________________________________________________`,
  },
  {
    title: 'The Stowaway',
    year: '2024',
    caption: 'he is in the corner of every photograph you have not seen.',
    art: String.raw`
   .                                                                    .
                                                                    .
                                                              .

                                                                 .

                                                                    .



                                                                       .



                                                                    .


                                                                .
                                                              .
                                                       .   /.\
                                                          /  \
                                                         /    \
                                                        '______'`,
  },
  {
    title: 'Salt Field',
    year: '2023',
    caption: 'the photograph after the photograph.',
    art: String.raw`
   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
     .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
     .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
     .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
     .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
     .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
     .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .
   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .   .`,
  },
  {
    title: 'Letter, Unsent',
    year: '2024',
    caption: 'still in the drawer. ledger 7 of 7.',
    art: String.raw`
   _______________________________________________________________
   |                                                             |
   |   dear ____________,                                        |
   |                                                             |
   |   i think about tuesday more than is reasonable. you wore   |
   |   the lighter coat. we did not say anything about it.       |
   |                                                             |
   |   if you read this you will know it was for you. if you     |
   |   do not read this it is still for you. so. either way.     |
   |                                                             |
   |                                          ─ ___________      |
   |_____________________________________________________________|`,
  },
  {
    title: 'Artificial Gallery (floor plan)',
    year: '2024',
    caption: 'three rooms. one visitor.',
    art: String.raw`
   ┌──────────────────────────┬──────────────────────────────────┐
   │                          │                                  │
   │    ROOM I                │    ROOM II                       │
   │    "harbor works"        │    "currency works"              │
   │                          │                                  │
   │      ▓     ▓     ▓       │       ▓        ▓                 │
   │                          │                                  │
   │                          │       ▓        ▓                 │
   │      ▓     ▓     ▓       │                                  │
   │                          │                                  │
   ├──────────────────────────┴──────────┐                       │
   │                                     │                       │
   │   ROOM III  "latent walk"           │                       │
   │                                     │                       │
   │   ▓   ▓   ▓   ▓   ▓   ▓             │       ▓        ▓      │
   │                                     │                       │
   │   ▓   ▓   ▓   ▓   ▓   ▓             │                       │
   │                                     │     ◦                 │
   └─────────────────────────────────────┴───────────────────────┘
                                              (visitor)`,
  },
];

// Merge static + video-generated works. Video works come first when present
// so the visitor sees the real material before the placeholder compositions.
export const WORKS: GalleryWork[] = [...VIDEO_WORKS, ...STATIC_WORKS];
